version: '3.8'

services:
  agent-environment:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: agent_environment
    shm_size: '2gb'
    ports:
      - "8080:8080" # VNC Port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      # --- FINAL, MORE LENIENT HEALTHCHECK ---
      # Gives the container a longer startup period before the first check
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s # Increased startup period to 45 seconds

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000" # FastAPI Port
    volumes:
      - ./backend:/app/backend
      - ../computer_use_demo:/app/computer_use_demo
    depends_on:
      agent-environment:
        condition: service_healthy
    env_file:
      - ./backend/.env

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend